### ISSUE TITLE
Developer Guide feedback

### ISSUE THREAD

**Issue by leowweixiang** [AY2021S1-CS2113T-F11-3/tp#192]
- [x] In the final version, be sure to fill in 1.1 and 1.2
- [x] Figure numbers
- [x] Remove names in the final version
- [x] 3.1 UI Component: Class Diagram is confusing in that in the architecture diagram, UI pointed to others whereas now others point to UI. I recommend that class diagram of the UI component focus on the classes **inside** the UI component. E.g. What you have done for Logic
- [x] 3.2 Visible `:information_source:`
- [x] 3.3 Model Component: Highlight the names of the objects e.g. "stores an `Access` object"
- [x] Standardise the UML tools used. E.g. Class diagram for AddModuleCommand in 4.1.1 different from 3.X diagrams. Same for sequence diagrams
- [x] 4.1.1 Explain the feature, a one-liner suffices like e.g. in 4.1.2 "the list modules feature allows..." and 4.1.3 "the edit modules..."
- [x] 4.1.1: A box or cell to encircle the steps involved may be good; else, bullet points like in 4.1.2
- [x] AddModule and AddChapter has class diagrams for the Commands whereas the others do not, recommend adding them for all the features, esp the ones with sequence diagrams
- [x] 4.3.6 Class diagram can be scaled down. Also, extra duplicate sequence diagram
- [x] Sequence diagrams of Commands: IMO if there's an issue with space, you don't have to show the Parser creating the specific Commands: Just show what happens when the execute() of the Commands are called
- [x] On both Firefox and Chrome with a 14.1" screen, there seems to be quite a bit of wasted space with wide left and right margins. It still looks tidy, so it's up to you if this is an issue

**Comment by woozije** [comment]
Fixed
